name: Deploy Tripinary to Vercel

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: 🚀 Deploy to Vercel
        run: |
          npm install -g vercel
          vercel --prod --yes --token=$VERCEL_TOKEN \
            --project-id=$VERCEL_PROJECT_ID
